2st task2
js-tasks-ru/js-20200821-3_nikita28 pull request #2
Opened 2020-08-26 21:58 UTC by Nikita7795

2020-08-26 22:05 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-08-27 09:51 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +             return arr.sort(new Intl.Collator(undefined , {caseFirst : "upper"}).compare).slice()
у Вас есть дублирующий код: строки 9 и 13, попробуйте избавиться от дублирования

Также, необходимо скопировать массив в самом начале функции перед всеми последующими манипуляциями с ним, Вы делаете это через `slice()`

2020-08-27 09:52 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let arrFruit = Object.entries(obj)
должна ли данная переменная быть объявлена через `let`?

2020-08-27 09:52 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let result = []
должна ли данная переменная быть объявлена через `let`?

2020-08-27 09:53 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let arrFruit = Object.entries(obj)
название `arrFruit` не совсем удачное, да в документации приводится пример с фруктами, но если мы будем использовать данную функцию на объекте в котором хранятся данные о машинах или о людях?

2020-08-27 09:54 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let arrFruit = Object.entries(obj)
см. коменты в задаче `pick` - здесь аналогичная ситуация

2020-08-27 09:54 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-08-27 16:34 UTC, jsru commented
@dosandk ping :)

2020-08-27 16:36 UTC, Nikita7795 commented
здравствуйте

2020-08-27 16:41 UTC, Nikita7795 commented
Здравствуйте
1.в 1 задании исправил: скопировал массив вначале функции и убрал дублирующие элементы.
2. назвал переменные через const , и поменял название массива arrFruit на arrObj
3.аналогично 2 задачи

2020-08-27 17:06 UTC, Nikita7795 commented
> Здравствуйте
> 1.в 1 задании исправил: скопировал массив вначале функции и убрал дублирующие элементы.
> 2. назвал переменные через const , и поменял название массива arrFruit на arrObj
> 3.аналогично 2 задачи

в 2st загрузилось почему-то две задачи, добавил третью задачу в 2с

2020-08-27 17:07 UTC, jsru commented
@dosandk ping :)

2020-08-28 09:58 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +   const arrSort = arr.concat()
есть более короткий и современный способ скопировать массив:
```
const copyArr = [...arr];
```

2020-08-28 09:59 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +   if (param == 'asc') {
`==` - такого оператора нет в JS

2020-08-28 10:01 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return arrSort.sort(collator.compare).reverse()
Здесь происходит лишняя операция `reverse`.
Необходимо сортировать массив сразу в нужном порядке, подумайте как это можно сделать

2020-08-28 10:02 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let i = 0; i < arrObj.length; i++) {
Есть ряд более удобных способов итерировать массив, один из них - встроенный метод `forEach` и цикл `for...of` 
Подробнее можно почитать здесь https://jstips.space/loops/

2020-08-28 10:03 UTC, dosandk requested changes
необходимо исправить функцию `sortStrings`

2020-08-28 14:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-08-30 14:43 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const results = []
почему бы сразу не положить результат итерации в объект?
Это позволило бы избавиться от операции `Object.fromEntries`

2020-08-30 14:45 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +   if (param === 'asc') {
```
const direction = {
  asc: 1,
  desc: -1
};

return arrSort.sort((a, b) => direction[param] * collator.compare(a, b));
```

2020-08-30 14:46 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +   if (param === 'asc') {
такая запись даст явное понимание что у нас есть 2 направления сортировки: `asc` и `desc`, а также позволит использовать один `return` что предпочтительнее двум в данном примере

2020-08-30 14:46 UTC, dosandk requested changes
необходимо поправить задачи `pick` и `omit`

2020-08-30 17:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-08-30 17:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
- should return array with uniq values
- should return empty array if was passed array without values
- should return empty array if arguments wasn't passed
```

2020-08-30 19:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
createGetter
- should return existed properties
- should return "undefined" for properties which does not exist
- gets obj.property
- returns undefined for no property
- gets obj.nested.property
- returns undefined for no nested.property
- gets more.nested.property
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
- should remove an identical consecutive characters that exceed the specified size
- should return empty string if it was passed to function like an argument
- should return empty string if "size" equal 0
- should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should return "undefined" if object wasn't passed
- should swap keys and values and return new object
- should return empty object if was passed object without values
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
- should return array with uniq values
- should return empty array if was passed array without values
- should return empty array if arguments wasn't passed
```

2020-08-30 19:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-08-30 19:59 UTC, Nikita7795 commented
а можно создать новый PR пока старый не закрыт? у меня автоматически в этот добавляет. Я хотел дз 3 урока в новый добавить

2020-08-31 16:37 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
good 👍

2020-08-31 16:38 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        if (fields.includes(key) === true) {
такие проверки стоит сокращать
```
 if (fields.includes(key)) {
```

2020-08-31 16:38 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (fields.includes(key) === false) {
такие проверки стоит сокращать
```
 if (!fields.includes(key)) 
```

2020-08-31 16:39 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            if (objResult === undefined) {
было бы неплохо избавиться от явного возврата `undefined`

2020-08-31 16:42 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    if (obj === undefined) {
было бы неплохо избавиться от явного возврата undefined

2020-08-31 16:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set(arr))
более короткая запись `return [...new Set('arr')]`

2020-08-31 16:43 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-09-01 08:25 UTC, Nikita7795 commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            if (objResult === undefined) {
Исправил

2020-09-01 08:25 UTC, Nikita7795 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    if (obj === undefined) {
Исправил

2020-09-01 08:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-01 10:43 UTC, dosandk approved these changes
good 👍

2020-09-01 10:44 UTC, merged